# -*- coding: utf-8 -*-
"""Scientific Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1steELPI_6dZfcgu43U_pqEGZ73IJD88j
"""

import math
import ipywidgets as widgets
from IPython.display import display

"""Calculator Display & History"""

screen = widgets.Text(value="", layout=widgets.Layout(width="320px", height="40px"))
history_box = widgets.VBox()

# Button Click
def on_click(b):
    if b.description == "=":
        try:
            expr = screen.value.replace("√", "math.sqrt").replace("^", "**")
            expr = expr.replace("sin", "math.sin(math.radians")
            expr = expr.replace("cos", "math.cos(math.radians")
            expr = expr.replace("tan", "math.tan(math.radians")
            expr = expr.replace("log", "math.log10")
            result = eval(expr + ")" * expr.count("(math"))


            history_box.children += (widgets.Label(f"{screen.value} = {result}"),)
            screen.value = str(result)
        except:
            screen.value = "Error"
    elif b.description == "C":
        screen.value = ""
    elif b.description == "⌫":
        screen.value = screen.value[:-1]
    else:
        screen.value += b.description

# Button Maker
def make_button(text, color="lightblue"):
    btn = widgets.Button(description=text, layout=widgets.Layout(width="60px", height="50px"))
    btn.style.button_color = color
    btn.on_click(on_click)
    return btn

"""Calculator Buttons Layout"""

buttons = [
    ["7", "8", "9", "/", "sin"],
    ["4", "5", "6", "*", "cos"],
    ["1", "2", "3", "-", "tan"],
    ["0", ".", "^", "+", "log"],
    ["√", "(", ")", "⌫", "C"],
    ["="]
]

display(screen)

for row in buttons:
    row_widgets = []
    for label in row:
        color = "lightblue"
        if label == "=":
            color = "orange"
        elif label == "C":
            color = "red"
        elif label == "⌫":
            color = "yellow"
        elif label in ["sin", "cos", "tan", "log", "√"]:
            color = "lightgreen"

        btn = make_button(label, color)
        btn.on_click(on_click)
        row_widgets.append(btn)

    display(widgets.HBox(row_widgets))

print("📝 Calculation History:")
display(history_box)